### ISSUE TITLE
make links to section headings possible.

### ISSUE THREAD

**Issue by ghost** [neomutt/neomutt.github.io#25]
Our README.md file has sections, to which links are possible: [https://github.com/neomutt/neomutt#where-is-neomutt](https://github.com/neomutt/neomutt#where-is-neomutt).

I think it'd be nice to implement that also on our website.

**Comment by flatcap** [comment]
Good idea.
Anchors are created automatically for markdown, but it's a good idea to override them.
This is because our site has a fixed banner which means the offsets aren't visible:

See the differences between:
- Preparation (automatic) -- https://www.neomutt.org/run/release#preparation
- Installation (overridden) -- https://www.neomutt.org/distro/fedora#install

Markdown:
- Automatic -- `## Preparation`
- Overridden -- `## Installation <a class="offset" id="install"></a>`

Note the override also customises the name of the anchor.
